### ISSUE TITLE
Enable the forkserver to avoid main-process forks

### ISSUE THREAD

**Issue by waddlesplash** [kenz-gelsoft/gecko-dev#102]
I noticed that the browser was still `fork`'ing even long after startup, and upon investigation it isn't due to a suboptimal `posix_spawn` invocation. This is slow, as it means we have to remap the entire address space of the parent process as read-only every single time it happens.

Poking around a bit, it appears that one of the key culprits is this: https://searchfox.org/mozilla-esr128/source/js/src/shell/js.cpp#6602

Looking in that source file, it appears the solution used for `XP_WIN` should work on Haiku with `posix_spawn` as well: pass the relevant FDs in command-line arguments. (On Haiku, when there aren't any extra "actions", `posix_spawn` doesn't `fork` at all. We could of course optimize it to never fork in the first place, also. And I bet that upstream would accept a patch that changes this code to use `posix_spawn` with the `fileactions` methods, which will provide a nice efficiency gain on Linux, the BSDs, and elsewhere, too.)

**Comment by waddlesplash** [comment]
In some discussion with the SpiderMonkey developers, it turns out that this method isn't used in the browser itself, and the stack trace I was seeing that seemed to be pointed to it was almost totally bogus. Instead the real culprit is `LaunchApp`.

It appears that there's a "forkserver" option which Linux and the BSDs use to avoid the parent process forking. There's a simple build option for it: https://searchfox.org/mozilla-central/source/toolkit/moz.configure#3039-3046

So, we should just enable that, then.

**Comment by waddlesplash** [comment]
I also filed a ticket about the Debugger stack traces being completely wrong: https://dev.haiku-os.org/ticket/19309

**Comment by kenz-gelsoft** [comment]
not js/shell but forkserver it makes sense.

I don't think simply enabling forkserver will work, but let's try. When I have enough build time. (I consumed all weekdays in last week for  #97 .)
