### ISSUE TITLE
Clean up Haiku package dependencies

### ISSUE THREAD

**Issue by kenz-gelsoft** [kenz-gelsoft/gecko-dev#26]
- [x] Do not install llvm12 in `./mach bootstrap`
  - as we now support following compilers (at least):
    - LLVM12
    - LLVM17
- [x] Prefer `pkg-config` over `pkgconf`
- [x] Add some more deps to install
  - nspr_devel
  - libvpx_devel
  - libevent_devel
  - dbus_devel

**Comment by X547** [comment]
Also is `pkgconf` really needed? It conflicts with `pkg-config` that is more common on Haiku.

**Comment by kenz-gelsoft** [comment]
OK I'll check that too in this cleanup.

**Comment by jessicah** [comment]
Missing packages:
- nspr_devel
- libvpx_devel
- libevent_devel
- dbus_devel

**Comment by kenz-gelsoft** [comment]
Thanks it helps!

**Comment by kenz-gelsoft** [comment]
I updated them in b2986cd6c5cfb723747797a20333158dd940b679 part of anothr PR https://github.com/kenz-gelsoft/gecko-dev/pull/32

**Comment by kenz-gelsoft** [comment]
Merged them.
