### ISSUE TITLE
Run without OpenGL?

### ISSUE THREAD

**Issue by waddlesplash** [kenz-gelsoft/gecko-dev#27]
So, the "elephant in the room" is whether we will have this port in the depot for beta 5 (upcoming in the next few weeks.) To use EGL needs the new Mesa+GLvnd stack, which we have not enabled yet because for a while it was broken, and now it's been mostly fixed but is still poorly tested. I would really rather we not upgrade Mesa right before the release and potentially break things that are currently working.

As I understand it, Gecko can run without any hardware acceleration, and I think even without an OpenGL context available? So this should be possible on Haiku as well. Looking at the first stack trace posted on the forum, it appears we are hitting an assert in Mesa EGL code. The EGL in the current Mesa is broken, so if we just disabled it entirely (had it return errors instead of crashing), would that be sufficient? Would Gecko then initialize all the way without an OpenGL context?

That way we can get Gecko in the package depot, before the release, and work on getting the newer Mesa available after the beta5 release without rushing things and with more time to test.

CC @X547.

**Comment by X547** [comment]
It seems run with `glvnd` installed without any actual OpenGL drivers installed.

**Comment by kenz-gelsoft** [comment]
I got following rendering with current mesa from HaikuDepot. (Though it immediately crashes)

![it_shows_something](https://github.com/user-attachments/assets/74d1934c-715f-4624-b0e5-e88c121f7519)

X512 said me to install `glvnd` manually, if that works well, I don't think we need to upgrade new mesa which not tested enough.

**Comment by X547** [comment]
> The EGL in the current Mesa is broken, so if we just disabled it entirely 

Yes, it should be disabled (maybe even removed from build).

**Comment by waddlesplash** [comment]
EGL disabled in Mesa. Startup still works, and now without the glxtest crash.
