### ISSUE TITLE
KDL by closing window (or other operation)

### ISSUE THREAD

**Issue by kenz-gelsoft** [kenz-gelsoft/gecko-dev#30]
![IMG_6994](https://github.com/user-attachments/assets/69ad35bd-afca-442e-a292-8c1e3644e361)

- After closing browser window (Highly reproducible)
- Or sometimes it happens by launching and just waiting a few seconds

**Comment by kenz-gelsoft** [comment]
@waddlesplash

Whole debug build is 984MB in bzip2, are there handy upload site to host such a large binary?

**Comment by waddlesplash** [comment]
You can probably post it on GitHub Releases temporarily?

**Comment by kenz-gelsoft** [comment]
I don't have (can't find) a FAT32 thumb drive now. As I don't believe uploading such a large file from Haiku would succeed. Please wait a few days...

(I'm going to bed)

**Comment by jessicah** [comment]
You can use sshfs to transfer to another machine, see https://jessicah.github.io/using-sshfs

**Comment by kenz-gelsoft** [comment]
@waddlesplash 

https://github.com/kenz-gelsoft/gecko-dev/releases/tag/HAIKU128_DEBUG20240813

This should contain debugging symbols, my source code path is /boot/home/src/gecko-dev.

I don't know if it works by just unpacking source-tree.

And my binary path is /boot/home/src/gecko-dev/obj-ff-dbg/dist. I compressed this directory into .tbz2.

```
~/src/gecko-dev> ./mach run
 0:00.49 /boot/home/src/gecko-dev/obj-ff-dbg/dist/bin/firefox -no-remote -profile /boot/home/src/gecko-dev/obj-ff-dbg/tmp/profile-default
Error: no DISPLAY environment variable specified
[525, Unnamed thread 1192c1b80b20] WARNING: XPCOM object StringBuffer released from static ctor/dtor: file /boot/home/src/gecko-dev/xpcom/base/nsTraceRefcnt.cpp:216
```

You can't `./mach run` without making development environment from source, I think. You can launch firefox by following command line
```
# export necessary environment variable for wayland
export WAYLAND_DISPLAY=:0
# run command line `./mach run` builds up for me
/boot/home/src/gecko-dev/obj-ff-dbg/dist/bin/firefox -no-remote -profile /boot/home/src/gecko-dev/obj-ff-dbg/tmp/profile-default
```

**Comment by waddlesplash** [comment]
Fails to start with:
```
Couldn't load XPCOM.
```
strace:
```
[   311] open(0xffffffff, "/boot/home/Desktop/dist/bin/dependentlibs.list", 0, 0x0) = 0x80006003 No such file or directory (141 us)
```
```
$ ls -al bin/dependentlibs.list
lrwxrwxrwx 1 user root 46 Aug 13 10:27 bin/dependentlibs.list -> ../../toolkit/library/build/dependentlibs.list
```
Which of course doesn't exist.

**Comment by kenz-gelsoft** [comment]
Oh, I missed to collect symlinked files...

I'll re-update binary tonight in JST, it may be multiple gigabytes archive.

me: don't forget `-h` option to tar

**Comment by waddlesplash** [comment]
Is the whole archive necessary? It looks like just a few symlinked files are needed. I guess you can test yourself by copying the directory out of your build environment and then making sure it runs.

**Comment by waddlesplash** [comment]
BTW, I think that KDL is continuable. It may leave the kernel VM in an invalid state, though, but at least you can avoid the reboot (and copy the full panic out of the syslog.)

**Comment by kenz-gelsoft** [comment]
Yes I will test before re-upload, firefox build artifact consists from many files so It is easier repackage them.

**Comment by kenz-gelsoft** [comment]
@waddlesplash re-uploaded.

https://github.com/kenz-gelsoft/gecko-dev/releases/tag/HAIKU128_DEBUG20240814

**Comment by diversys** [comment]
Also KDLs for me 2 seconds after Firefox window appears. I didn't even need to close any windows.

**Comment by waddlesplash** [comment]
Indeed, same here. However I also have the problem that Firefox doesn't seem to accept any input? When I first started it, I specified a profile directory that didn't exist, and got an error dialog box; but I couldn't click "OK" or tab or anything else in it (it resized OK, though.)

**Comment by waddlesplash** [comment]
Before I installed all the dependencies I got a crash on startup in runtime_loader; fixed that in [hrev57970](https://git.haiku-os.org/haiku/tag/?h=hrev57970).

The KDL itself happens because we are trying to merge a VMAnonymousNoSwapCache with a VMAnonymousCache. The AnonymousNoSwapCache is a vnode cache that comes from RAMFS. At the point a RAMFS vnode is deleted, we shouldn't have any remaining consumers of its caches, so this looks like a reference-counting bug. The lone consumer does have one area mapping (`libnspr4.so mmap area`).

**Comment by kenz-gelsoft** [comment]
> However I also have the problem that Firefox doesn't seem to accept any input? When I first started it, I specified a profile directory that didn't exist, and got an error dialog box; but I couldn't click "OK" or tab or anything else in it (it resized OK, though.)

Yes, I also encounter that. X512 said it is wayland-server's problem, but it is not clear he encounters same problem or not.

- https://github.com/kenz-gelsoft/gecko-dev/issues/10#issuecomment-2282841037
- https://github.com/kenz-gelsoft/gecko-dev/wiki#current-status

For input issue, I can dig into that by printf-debug, or attacing great GSoC'ed GCC!

For KDL, your help is very welcome!

**Comment by X547** [comment]
> Yes, I also encounter that. X512 said it is wayland-server's problem, but it is not clear he encounters same problem or not.

Input is wayland-server problem. It get confused by subsurface created by Firefox. Input should be delivered to root surface, but is currently misdelivered to subsurface.

I have draft fix locally.

**Comment by kenz-gelsoft** [comment]
> I have draft fix locally.

@X547 great to hear that!

**Comment by kenz-gelsoft** [comment]
> Also KDLs for me 2 seconds after Firefox window appears. I didn't even need to close any windows.

I didn't find 100% reproducible condition for this, indeed I have seen this pattern sometimes, too.

**Comment by waddlesplash** [comment]
I've figured out the cause of the KDLs and am working on a fix.

**Comment by X547** [comment]
> > I have draft fix locally.
> 
> @X547 great to hear that!

https://github.com/X547/wayland-server/tree/work

**Comment by kenz-gelsoft** [comment]
> At the point a RAMFS vnode is deleted, we shouldn't have any remaining consumers of its caches, so this looks like a reference-counting bug. The lone consumer does have one area mapping (`libnspr4.so mmap area`).

For NSPR, I just chose to integrate Haikuports version as-is in porting process. I don't know and investigate at all, how much it was tested by other packages. There are possibility compilation option mismatch c.f. positive vs negative POSIX error value.

**Comment by waddlesplash** [comment]
That shouldn't matter, whatever happens in userland shouldn't cause a kernel crash and certainly not this kernel crash.

**Comment by diversys** [comment]
While we're waiting for a fix, you can workaround it by unmounting RAMFS:
`unmount /var/shared_memory`
It seems to launch much slower, though.

**Comment by waddlesplash** [comment]
KDLs fixed in hrev57971.

**Comment by kenz-gelsoft** [comment]
What a quick fix! I’ll verify and will close this issue tonight (or tomorrow build?).

**Comment by waddlesplash** [comment]
The standard nightly builds happen around 2am EST (about 7 hours from now.)

**Comment by kenz-gelsoft** [comment]
I verified its not enter KDL anymore (as far as I tested).

I need to debug why it crashes, but closing this. Thanks.

**Comment by X547** [comment]
> I verified its not enter KDL anymore (as far as I tested).

Did you managed to get input working?

**Comment by kenz-gelsoft** [comment]
No, I will open new issue for that.

I tried building your work branch with the Haikuporter and the recipe edited, but was not success yet.

I study Haikuporter more and will retry.
