### ISSUE TITLE
Incorporate BGL by hacking the in-proc wayland-server

### ISSUE THREAD

**Issue by kenz-gelsoft** [kenz-gelsoft/gecko-dev#5]
As a temporary work around lack of EGL suppot of the wayland server.

If I changed the View it creates from BView to BGLView and add a way to get the pointer,  can my app logic draw triangles with it?

- [ ] build wayland-server manually
- [ ] use it with simple wayland sample program
- [ ] start hacking!

**Comment by kenz-gelsoft** [comment]
https://discuss.haiku-os.org/t/qt-5-3-for-haiku-progress/3698/19?u=kenz

**Comment by X547** [comment]
Wayland server do not need any kind of OpenGL handling, it just receive bitmaps already rendered by client. All OpenGL handling is done on client side. Recently I managed to build Mesa with EGL Wayland support (with non-functional libdrm) and it worked at least with GTK OpenGL demos.

**Comment by kenz-gelsoft** [comment]
@X547 thank you for input.

I see changing wayland-server (add-on) code is not necessary to use EGL.

I’ll try MESA ｗ/ EGL wayland support when I can work on GL integration.

**Comment by kenz-gelsoft** [comment]
This issue itself is invalid with my misunderstanding.

Close.

**Comment by X547** [comment]
@kenz-gelsoft

Sorry, can you recheck and update Firefox build instructions on latest Haiku nightly? It seems packages versions are changed and instruction is not working anymore. I have absolute no idea how Firefox build system is working.

**Comment by kenz-gelsoft** [comment]
Though I want to change porting target to newer version (esr102 to esr128), OK I will take some time to  update build instruction.

Maybe it needs some more fixes other than GL integration I guess.

**Comment by X547** [comment]
It will be nice if it can use LLVM 17.
