### ISSUE TITLE
Support IME input (on Wayland GTK+)

### ISSUE THREAD

**Issue by kenz-gelsoft** [kenz-gelsoft/gecko-dev#59]
https://www.haiku-os.org/legacy-docs/bebook/TheInputServer_Introduction.html

committed characters sent by B_KEY_DOWN, but maybe ignored in Wayland emulation.

- [x] investigate whether gtk can handle unicode char event
- [ ] make empty immodule on Linux
- [ ] port it and connect IME API

**Comment by kenz-gelsoft** [comment]
> investigate whether gtk can handle unicode char event

no way to do that
- https://docs.gtk.org/gtk3/input-handling.html
- https://docs.gtk.org/gdk3/struct.EventKey.html

**Comment by kenz-gelsoft** [comment]
> make empty immodule on Linux

Will write with ~~vala +~~ C++, by referring uim's implementation (as it is BSD license).

**Comment by X547** [comment]
It need implementing text input protocol on wayland-server side.

**Comment by kenz-gelsoft** [comment]
Thanks for the info. I thought it is optional for toolkit agnostic better integration as that protocol was experimental.

I will pending this for now.

**Comment by kenz-gelsoft** [comment]
oops, I said about input method protocol (experimental)
- https://wayland.app/protocols/input-method-unstable-v2

there is resemble but different protocol you said (unstable).
- https://wayland.app/protocols/text-input-unstable-v3

...or it was renamed?

no, the former is for wayland native input method, the latter is for compositor to support non-ascii multi-stage text input. I see.

**Comment by X547** [comment]
> * https://wayland.app/protocols/text-input-unstable-v3

This one should be implemented in wayland-server I suppose. It is supported by GTK.

> https://wayland.app/protocols/input-method-unstable-v2

This protocol is for implementing input methods, not using it.

**Comment by kenz-gelsoft** [comment]
My next interest is this. I studied how wayland-server works somewhat. I want to try hacking this.

**Comment by waddlesplash** [comment]
FWIW, in the original version of the GTK3 port (the one that used Xlibe rather than the Wayland layer), I added a hack to use Xlibe's keyboard routines, that do use the UTF-8 data Haiku passes in rather than processing the keymap manually: https://github.com/haikuports/haikuports/blob/ecc619f548dced5090dc69a2a2a4543cb118795e/x11-libs/gtk3/patches/gtk3-3.24.30.patchset#L842

**Comment by kenz-gelsoft** [comment]
@waddlesplash thank you for that info. I'll refer when I'll implement this.

**Comment by X547** [comment]
It should be possible to implement input method integration, not just inputting in a separate window and sending result string to application after confirmation.

**Comment by X547** [comment]
Added wayland-server issue: https://github.com/X547/wayland-server/issues/14. It is likely nothing is needed to change as Firefox or GTK side.

**Comment by kenz-gelsoft** [comment]
Thanks.
