### ISSUE TITLE
Numeric pad doesn't work (Wayland GTK issue?)

### ISSUE THREAD

**Issue by kenz-gelsoft** [kenz-gelsoft/gecko-dev#61]
> Numeric pad (normal USB keyboard) doesn’t work in Firefox but works in other haiku app.

reported at https://discuss.haiku-os.org/t/progress-on-porting-firefox/13493/233?u=kenz

**Comment by X547** [comment]
Duplicate of https://github.com/X547/wayland-server/issues/3.

**Comment by kenz-gelsoft** [comment]
I didn’t think this is same issue.

OK closing this issue. Thanks.

**Comment by Bebertux** [comment]
I stil have issue with numeric pad and Iceweasel. (keyboard usb - 105 keys - AZERTY - FR ) (tested PS2 keyboard : same problem)
Numeric pad works always as directions keys, never as number. Verr Num changes nothing : LED ON or OFF same behaviour.

I also have problem with Alt-Gr.

I don't think this issue can be closed.
Thanks
