### ISSUE TITLE
Creating IPC I/O thread misbehaves somewhat and then the main thread quits.

### ISSUE THREAD

**Issue by kenz-gelsoft** [kenz-gelsoft/gecko-dev#8]
Parent thread "MainThread" creates new thread with pthread_create() here

https://searchfox.org/mozilla-esr102/source/ipc/chromium/src/base/platform_thread_posix.cc#123

Parent thread's pthread_create() successfully call _kern_spawn_thread() and child thread is spawned.

After that, the child thread try to create new thread again (~~it looks same code, but it should be in another logic which specified ThreadFunc and its Delegate passed with~~ [confirmed](https://github.com/kenz-gelsoft/gecko-dev/issues/8#issuecomment-1565209477)).

Child thread's pthread_create() calles _kern_spawn_thread(), after returning there, parent thread quit.

(Is it crash? or something timeout and quit by itself?)

**Comment by kenz-gelsoft** [comment]
At first, I suspect it can mix some libraries use fork() and the other code Haiku's spawn_thread(), then Haiku made it fail as described in https://www.haiku-os.org/legacy-docs/bebook/TheKernelKit_ThreadsAndTeams_Overview.html.

But, regarding with GTK/GDK and wayland-server, it doesn't contain call of spawn_thread(), so this is not the case probably.

**Comment by kenz-gelsoft** [comment]
Parent thread

![screenshot12](https://github.com/kenz-gelsoft/gecko-dev/assets/1608997/686436d2-bb4f-4242-ae32-c129d1c35494)

Child thread breaks here

![screenshot13](https://github.com/kenz-gelsoft/gecko-dev/assets/1608997/829e5344-85c6-41c4-9373-25276f37fb6b)

Step over calling syscall in _kern_spawn_thread, then parent thread 24239 quits

![screenshot14](https://github.com/kenz-gelsoft/gecko-dev/assets/1608997/6bdc117c-454a-4d5a-9d20-c8514bf02df8)

**Comment by kenz-gelsoft** [comment]
Parent thread wait for child thread forever

https://searchfox.org/mozilla-esr102/source/ipc/chromium/src/base/thread.cc#100

![screenshot15](https://github.com/kenz-gelsoft/gecko-dev/assets/1608997/eca8c7ef-b07a-4dec-ad82-0780a5f16399)

https://searchfox.org/mozilla-esr102/source/ipc/chromium/src/base/condition_variable_posix.cc#60

**Comment by kenz-gelsoft** [comment]
If these thread handling depends on thread name, we disabled it in ~~fd7609cb1093976cdc0237fcd2200c24b48b794e~~, 7d9431bd6a9fccf0248ac14e21c4a57e9f5aa6f3 to compile...

Hmm, but it looks changes live in modules which isn't reached yet.

**Comment by kenz-gelsoft** [comment]
Condition variable in Haiku is something special

https://www.haiku-os.org/blog/waddlesplash/2023-04-24_condition_variables/

**Comment by kenz-gelsoft** [comment]
Child thread select following
```c++
void Thread::ThreadMain() {
  nsCOMPtr<nsIThread> xpcomThread;
  auto loopType = startup_data_->options.message_loop_type;
  if (loopType == MessageLoop::TYPE_MOZILLA_NONMAINTHREAD ||
      loopType == MessageLoop::TYPE_MOZILLA_NONMAINUITHREAD) {
    auto queue = mozilla::MakeRefPtr<mozilla::ThreadEventQueue>(
        mozilla::MakeUnique<mozilla::EventQueue>());
    xpcomThread = nsThreadManager::get().CreateCurrentThread(
        queue, nsThread::NOT_MAIN_THREAD);
  } else {
>    xpcomThread = NS_GetCurrentThread();
  }
```

**Comment by kenz-gelsoft** [comment]
We're creating IO type thread
```c++
  if (XRE_IsParentProcess() &&
      !BrowserProcessSubThread::GetMessageLoop(BrowserProcessSubThread::IO)) {
    mozilla::UniquePtr<BrowserProcessSubThread> ioThread =
        mozilla::MakeUnique<BrowserProcessSubThread>(
            BrowserProcessSubThread::IO);

    base::Thread::Options options;
    options.message_loop_type = MessageLoop::TYPE_IO;
    if (NS_WARN_IF(!ioThread->StartWithOptions(options))) {
```
Should create `MessagePumpLibevent`. libevent path maybe not well tested with non-epoll()/kqueue().
```c++
  } else if (type_ == TYPE_IO) {
    pump_ = new base::MessagePumpLibevent();
  } else {
    pump_ = new base::MessagePumpDefault();
  }
#endif    // OS_POSIX
```

**Comment by kenz-gelsoft** [comment]
On creating `pipe()` here failed in _kern_create_pipe syscall.

https://searchfox.org/mozilla-esr102/source/ipc/chromium/src/third_party/libevent/evutil.c#2688

In-proc pipe-ing doesn't work on Haiku? Let's try #define HAVE_PIPE 0

**Comment by kenz-gelsoft** [comment]
Incremental rebuild of following change crashes weirdly. Clean building...

> Let's try #define HAVE_PIPE 0

**Comment by kenz-gelsoft** [comment]
system libevent may be used after  https://github.com/kenz-gelsoft/gecko-dev/issues/1

**Comment by kenz-gelsoft** [comment]
Haiku source tree seems no implementation of pipe
```
~/src/haiku> grep -R _kern_create_pipe .
./headers/private/system/syscalls.h:extern status_t             _kern_create_pipe(int *fds);
./src/bin/debug/strace/strace.cpp:      Syscall *createPipe = get_syscall("_kern_create_pipe");
./src/system/libroot/posix/unistd/pipe.c:       status_t error = _kern_create_pipe(streams);
./src/system/libroot/stubbed/libroot_stubs.c:void _kern_create_pipe() {}
./src/system/libroot/stubbed/libroot_stubs_legacy.c:void _kern_create_pipe() {}
```

**Comment by kenz-gelsoft** [comment]
Rebuilt binary with HAVE_PIPE 0 segv on the same _kern_spawn_thread call.

![screenshot16](https://github.com/kenz-gelsoft/gecko-dev/assets/1608997/c9063e7f-6414-41e0-9cb3-52959e35844a)

**Comment by kenz-gelsoft** [comment]
Will retest this with Haiku nightly.

**Comment by X547** [comment]
Fixed by following patch:

Problem was caused by function without return statement that triggers UB.

``` diff
diff --git a/ipc/chromium/src/base/platform_thread_posix.cc b/ipc/chromium/src/base/platform_thread_posix.cc
index 7c866b84c038..ab178ea20119 100644
--- a/ipc/chromium/src/base/platform_thread_posix.cc
+++ b/ipc/chromium/src/base/platform_thread_posix.cc
@@ -16,6 +16,8 @@
 #elif defined(OS_LINUX)
 #  include <sys/syscall.h>
 #  include <sys/prctl.h>
+#elif defined(__HAIKU__)
+#  include <OS.h>
 #endif
 
 #if !defined(OS_MACOSX)
@@ -59,6 +61,8 @@ PlatformThreadId PlatformThread::CurrentId() {
   return lwp_gettid();
 #elif defined(OS_FREEBSD)
   return pthread_getthreadid_np();
+#elif defined(__HAIKU__)
+  return find_thread(NULL);
 #endif
 }
 
```

**Comment by kenz-gelsoft** [comment]
Thanks a lot. I commited your changes in https://github.com/kenz-gelsoft/gecko-dev/issues/11#issuecomment-2261525040 on x512_fixes branch.

I'll try debugging with your changes.

**Comment by kenz-gelsoft** [comment]
This seems fixed by X512's patch https://github.com/kenz-gelsoft/gecko-dev/issues/8#issuecomment-2262697986

Thanks. closed.
